set_property PACKAGE_PIN B8 [get_ports FPGA_CLK_50MHZ]
# Define the 50 MHz main clock (Period = 20 ns)
create_clock -period 20.000 -name sys_clk_pin -waveform {0.000 10.000} -add [get_ports FPGA_CLK_50MHZ]
# Set a generic 2ns input delay for all inputs
set_input_delay -clock sys_clk_pin -add_delay 2.000 [get_ports {RESET_SW RS422_RX}]

# Set a generic 2ns output delay for all outputs
set_output_delay -clock sys_clk_pin -add_delay 2.000 [get_ports -filter { NAME =~  "*" && DIRECTION =~  "*OUT*" }]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_CLK_50MHZ]
set_property PACKAGE_PIN T9 [get_ports FP_STS1_GREEN]
set_property IOSTANDARD LVCMOS33 [get_ports FP_STS1_GREEN]
set_property PACKAGE_PIN T10 [get_ports FP_STS2_YELLOW]
set_property IOSTANDARD LVCMOS33 [get_ports FP_STS2_YELLOW]
set_property PACKAGE_PIN D10 [get_ports RESET_SW]
set_property PACKAGE_PIN P17 [get_ports RS422_RX]
set_property PACKAGE_PIN P15 [get_ports RS422_TX]
set_property PACKAGE_PIN T15 [get_ports RS422_TX_EN]
set_property PACKAGE_PIN T14 [get_ports RS422_TX_nEN]
set_property PACKAGE_PIN A8 [get_ports TP_CLK_TST]
set_property IOSTANDARD LVCMOS33 [get_ports RESET_SW]
set_property IOSTANDARD LVCMOS33 [get_ports RS422_RX]
set_property IOSTANDARD LVCMOS33 [get_ports RS422_TX]

set_property IOSTANDARD LVCMOS33 [get_ports RS422_TX_EN]
set_property IOSTANDARD LVCMOS33 [get_ports RS422_TX_nEN]
set_property IOSTANDARD LVCMOS33 [get_ports TP_CLK_TST]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F1_LD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F2_LD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[4]}]
set_property SLEW FAST [get_ports {F3_LD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F3_LD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_LE[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_LE[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_LE[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_LE[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_LE[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_LE[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_LE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_LE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_LE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_nLOE[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_LE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_nLOE[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_nLOE[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_nLOE[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_nLOE[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_nLOE[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_nLOE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_nLOE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_nLOE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {F_nLOE[0]}]
set_property PACKAGE_PIN F5 [get_ports {F1_LD[0]}]
set_property PACKAGE_PIN C6 [get_ports {F1_LD[1]}]
set_property PACKAGE_PIN C5 [get_ports {F1_LD[2]}]
set_property PACKAGE_PIN B7 [get_ports {F1_LD[3]}]
set_property PACKAGE_PIN B6 [get_ports {F1_LD[4]}]
set_property PACKAGE_PIN A6 [get_ports {F1_LD[5]}]
set_property PACKAGE_PIN A5 [get_ports {F1_LD[6]}]
set_property PACKAGE_PIN D8 [get_ports {F1_LD[7]}]
set_property PACKAGE_PIN C7 [get_ports {F1_LD[8]}]
set_property PACKAGE_PIN E6 [get_ports {F1_LD[9]}]
set_property PACKAGE_PIN E5 [get_ports {F1_LD[10]}]
set_property PACKAGE_PIN E7 [get_ports {F1_LD[11]}]
set_property PACKAGE_PIN D7 [get_ports {F1_LD[12]}]
set_property PACKAGE_PIN C4 [get_ports {F1_LD[13]}]
set_property PACKAGE_PIN B4 [get_ports {F1_LD[14]}]
set_property PACKAGE_PIN A4 [get_ports {F1_LD[15]}]
set_property PACKAGE_PIN B1 [get_ports {F2_LD[0]}]
set_property PACKAGE_PIN A1 [get_ports {F2_LD[1]}]
set_property PACKAGE_PIN B3 [get_ports {F2_LD[2]}]
set_property PACKAGE_PIN B2 [get_ports {F2_LD[3]}]
set_property PACKAGE_PIN D5 [get_ports {F2_LD[4]}]
set_property PACKAGE_PIN D4 [get_ports {F2_LD[5]}]
set_property PACKAGE_PIN E3 [get_ports {F2_LD[6]}]
set_property PACKAGE_PIN D3 [get_ports {F2_LD[7]}]
set_property PACKAGE_PIN F4 [get_ports {F2_LD[8]}]
set_property PACKAGE_PIN F3 [get_ports {F2_LD[9]}]
set_property PACKAGE_PIN E2 [get_ports {F2_LD[10]}]
set_property PACKAGE_PIN D2 [get_ports {F2_LD[11]}]
set_property PACKAGE_PIN H2 [get_ports {F2_LD[12]}]
set_property PACKAGE_PIN G2 [get_ports {F2_LD[13]}]
set_property PACKAGE_PIN C2 [get_ports {F2_LD[14]}]
set_property PACKAGE_PIN C1 [get_ports {F2_LD[15]}]
set_property PACKAGE_PIN G1 [get_ports {F3_LD[0]}]
set_property PACKAGE_PIN F1 [get_ports {F3_LD[1]}]
set_property PACKAGE_PIN E1 [get_ports {F3_LD[2]}]
set_property PACKAGE_PIN G6 [get_ports {F3_LD[3]}]
set_property PACKAGE_PIN F6 [get_ports {F3_LD[4]}]
set_property PACKAGE_PIN G4 [get_ports {F3_LD[5]}]
set_property PACKAGE_PIN G3 [get_ports {F3_LD[6]}]
set_property PACKAGE_PIN J4 [get_ports {F3_LD[7]}]
set_property PACKAGE_PIN H4 [get_ports {F3_LD[8]}]
set_property PACKAGE_PIN J3 [get_ports {F3_LD[9]}]
set_property PACKAGE_PIN J2 [get_ports {F3_LD[10]}]
set_property PACKAGE_PIN K2 [get_ports {F3_LD[11]}]
set_property PACKAGE_PIN K1 [get_ports {F3_LD[12]}]
set_property PACKAGE_PIN H6 [get_ports {F3_LD[13]}]
set_property PACKAGE_PIN H5 [get_ports {F3_LD[14]}]
set_property PACKAGE_PIN J5 [get_ports {F3_LD[15]}]
set_property PACKAGE_PIN E15 [get_ports {F_LE[0]}]
set_property PACKAGE_PIN E16 [get_ports {F_LE[1]}]
set_property PACKAGE_PIN D15 [get_ports {F_LE[2]}]
set_property PACKAGE_PIN C15 [get_ports {F_LE[3]}]
set_property PACKAGE_PIN H16 [get_ports {F_LE[4]}]
set_property PACKAGE_PIN G16 [get_ports {F_LE[5]}]
set_property PACKAGE_PIN F15 [get_ports {F_LE[6]}]
set_property PACKAGE_PIN F16 [get_ports {F_LE[7]}]
set_property PACKAGE_PIN H14 [get_ports {F_LE[8]}]
set_property PACKAGE_PIN G14 [get_ports {F_LE[9]}]
set_property PACKAGE_PIN R3 [get_ports {F_nLOE[0]}]
set_property PACKAGE_PIN T3 [get_ports {F_nLOE[1]}]
set_property PACKAGE_PIN T5 [get_ports {F_nLOE[2]}]
set_property PACKAGE_PIN T4 [get_ports {F_nLOE[3]}]
set_property PACKAGE_PIN N5 [get_ports {F_nLOE[4]}]
set_property PACKAGE_PIN P5 [get_ports {F_nLOE[5]}]
set_property PACKAGE_PIN P4 [get_ports {F_nLOE[6]}]
set_property PACKAGE_PIN P3 [get_ports {F_nLOE[7]}]
set_property PACKAGE_PIN P2 [get_ports {F_nLOE[8]}]
set_property PACKAGE_PIN R2 [get_ports {F_nLOE[9]}]
set_property SLEW SLOW [get_ports FP_STS1_GREEN]
set_property SLEW SLOW [get_ports FP_STS2_YELLOW]
set_property SLEW FAST [get_ports RS422_TX]
set_property SLEW FAST [get_ports RS422_TX_EN]
set_property SLEW FAST [get_ports RS422_TX_nEN]
set_property SLEW FAST [get_ports TP_CLK_TST]




set_property BITSTREAM.GENERAL.COMPRESS FALSE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
